// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "server/database/prisma/schema.prisma",
  migrations: {
    path: "server/database/prisma/migrations",
    seed: "tsx server/database/prisma/seed.ts",
  },
  datasource: {
    url: "file:./database/dev.db",
  },
});
